services:
  app:
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"

    environment:
      - APP_PORT=${APP_PORT}
      - REDIS_ADDR=${REDIS_ADDR}
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
